project_id = "xynwjqxprigmhctzurks"

[functions]

[functions.generate-appreciation]
verify_jwt = false

[functions.generate-class-appreciation]
verify_jwt = false

[functions.generate-reportcard-appreciation]
verify_jwt = false

[functions.generate-reportcard-summary]
verify_jwt = false

[functions.check-and-consume-credits]
verify_jwt = false

[functions.redeem-promo-code]
verify_jwt = false

[functions.admin-promo-codes]
verify_jwt = false
