project_id = "xynwjqxprigmhctzurks"

[functions]

[functions.generate-appreciation]
verify_jwt = false

[functions.generate-class-appreciation]
verify_jwt = false

[functions.generate-reportcard-appreciation]
verify_jwt = false

[functions.generate-reportcard-summary]
verify_jwt = false
